### ISSUE TITLE
Documentation how to get started

### ISSUE THREAD

**Issue by davecramer** [timbira/krahodb#3]
Any chance you could write up a short tutorial on how to get started ?

**Comment by eulerto** [comment]
commit 1b15f1491ce03e1c25efd4ae5fca85c860011108 added some basic instructions. Feel free to improve it.

**Comment by fabriziomello** [comment]
What about create a docker-compose to run a demo? Maybe creating another repo called `krahodb-demo` or `krahodb-tutorial`?

**Comment by davecramer** [comment]
I may have some cycles to work on this
